### ISSUE TITLE
Remove axios

### ISSUE THREAD

**Issue by vladimirvolek** [blockfrost/blockfrost-js#121]
Use https://www.npmjs.com/package/got

**Comment by karltaylor** [comment]
> Use https://www.npmjs.com/package/got

I'm just curois @vladimirvolek, why?

**Comment by vladimirvolek** [comment]
> > Use https://www.npmjs.com/package/got
> 
> I'm just curious @vladimirvolek, why?

yey hello!

The reason is that I don't like this error handling https://github.com/blockfrost/blockfrost-js/blob/master/src/utils/index.ts#L76
Also, we can remove one dependency `retry-axios` (https://www.npmjs.com/package/got#retry)
