### ISSUE TITLE
[SEND SIGNED TRANSACTION][TESTNET]

### ISSUE THREAD

**Issue by Hazhir007** [blockfrost/blockfrost-js#123]
hi i am wondering how can i send a signed transaction on test net on blockfrost, i got this cbor signed transaction:

83a4008182582051dfe50aa28c926860eb55e045e74fadeba91bf7ba1f476f25ef50a4b6be84a2000181825839000743d16cfe3c4fcc0c11c2403bbc10dbc7ecdd4477e053481a368e7a06e2ae44dff6770dc0f4ada3cf4cf2605008e27aecdb332ad349fda71903e8021a0002da5d031a0235cb63a100818258200ab4fa0e1714bbf27ca133e3b41359e6625b14de484fcc5e09c87be413ac8d7d584050a014809ebc58e0bb30d352b239a42a3af1dcfcac50299e363ee984739fc697c0ad1eefe5b0b0f9811a353b15570ab0009ffd8f4987eee6ccef6a124f637206f6

now i want to send this on postman or either with blockfrost.js i think by default blockfrost.js sets urls as mainnet how to switch to test net.

**Comment by Hazhir007** [comment]
i have wrote this but when running the script i get token mistmatch which i am sure the token is right:

`
import { BlockFrostAPI } from "@blockfrost/blockfrost-js";

async function main() {

    const API = new BlockFrostAPI({
        apiUrl: 'https://cardano-testnet.blockfrost.io/api/v0',
        projectId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', // see: https://blockfrost.io
    });

    console.log(API.apiUrl.toString())
    try {
        const latestBlock = await API.blocksLatest();
        const latestEpoch = await API.epochsLatest();
        const health = await API.health();
        const address = await API.addresses(
            'addr_test1qpv7yuh9zlp4nl0xgpanw6wg0k7q4xdezre40x9tmatxgxhhzk84wq3k8hrfgeada8ewr23y7hk6z88a2q0alf934tmqcvn6r8',
        );

        console.log('address', address);
        console.log('latestEpoch', latestEpoch);
        console.log('latestBlock', latestBlock);
        console.log('health', health);
    } catch (err) {
        console.log('error', err);
    }
}

main();
`

**Comment by vladimirvolek** [comment]
Hello!

Sure! Just set the parameter `isTesnet` to true.

```
const API = new BlockFrostAPI({
  projectId: 'YOUR API KEY HERE', // see: https://blockfrost.io
  isTestnet: true,
});
```

**Comment by Hazhir007** [comment]
> Hello!
> 
> Sure! Just set the parameter `isTestnet` to true.
> 
> ```
> const API = new BlockFrostAPI({
>   projectId: 'YOUR API KEY HERE', // see: https://blockfrost.io
>   isTestnet: true,
> });
> ```

thanks it's working

**Comment by Hazhir007** [comment]
when try to send the transaction i get a 500 Internal Server Error what can cause such thing?

here is my code:

```import { BlockFrostAPI } from "@blockfrost/blockfrost-js";

async function main() {

    const API = new BlockFrostAPI({
        isTestnet: true,
        projectId: 'xxxxxxxxxxxxxxxxxxxxxxxx', // see: https://blockfrost.io
    });

    console.log(API.apiUrl.toString())
    try {
        const latestBlock = await API.blocksLatest();
        const latestEpoch = await API.epochsLatest();
        const health = await API.health();

        const address = await API.addresses(
            'addr_test1qpv7yuh9zlp4nl0xgpanw6wg0k7q4xdezre40x9tmatxgxhhzk84wq3k8hrfgeada8ewr23y7hk6z88a2q0alf934tmqcvn6r8',
        );


        const submitTx = await API.txSubmit('83a4008182582051dfe50aa28c926860eb55e045e74fadeba91bf7ba1f476f25ef50a4b6be84a2000181825839000743d16cfe3c4fcc0c11c2403bbc10dbc7ecdd4477e053481a368e7a06e2ae44dff6770dc0f4ada3cf4cf2605008e27aecdb332ad349fda71903e8021a0002da5d031a0235cb63a100818258200ab4fa0e1714bbf27ca133e3b41359e6625b14de484fcc5e09c87be413ac8d7d584050a014809ebc58e0bb30d352b239a42a3af1dcfcac50299e363ee984739fc697c0ad1eefe5b0b0f9811a353b15570ab0009ffd8f4987eee6ccef6a124f637206f6');
        console.log('submitTx', submitTx);
        console.log('latestEpoch', latestEpoch);
        console.log('latestBlock', latestBlock);
        console.log('health', health);
    } catch (err) {
        console.log('error', err);
    }
}

main();```

**Comment by vladimirvolek** [comment]
Can you try again? 
You should see this.

```
error {
  error: 'Bad Request',
  message: 'transaction submit error ShelleyTxValidationError ShelleyBasedEraAlonzo (ApplyTxError [UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (OutputTooSmallUTxO [(Addr Testnet (KeyHashObj (KeyHash "0743d16cfe3c4fcc0c11c2403bbc10dbc7ecdd4477e053481a368e7a")) (StakeRefBase (KeyHashObj (KeyHash "06e2ae44dff6770dc0f4ada3cf4cf2605008e27aecdb332ad349fda7"))),Value 1000 (fromList []),SNothing)]))),UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (ValueNotConservedUTxO (Value 1000000000 (fromList [])) (Value 187973 (fromList []))))),UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (OutsideValidityIntervalUTxO (ValidityInterval {invalidBefore = SNothing, invalidHereafter = SJust (SlotNo 37079907)}) (SlotNo 37083558))))])',
  status_code: 400
}
```

**Comment by Hazhir007** [comment]
> Can you try again?
> You should see this.
> 
> ```
> error {
>   error: 'Bad Request',
>   message: 'transaction submit error ShelleyTxValidationError ShelleyBasedEraAlonzo (ApplyTxError [UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (OutputTooSmallUTxO [(Addr Testnet (KeyHashObj (KeyHash "0743d16cfe3c4fcc0c11c2403bbc10dbc7ecdd4477e053481a368e7a")) (StakeRefBase (KeyHashObj (KeyHash "06e2ae44dff6770dc0f4ada3cf4cf2605008e27aecdb332ad349fda7"))),Value 1000 (fromList []),SNothing)]))),UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (ValueNotConservedUTxO (Value 1000000000 (fromList [])) (Value 187973 (fromList []))))),UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (OutsideValidityIntervalUTxO (ValidityInterval {invalidBefore = SNothing, invalidHereafter = SJust (SlotNo 37079907)}) (SlotNo 37083558))))])',
>   status_code: 400
> }
> ```

yes now i see 400 error, but why? is my transaction incorrect?

**Comment by vladimirvolek** [comment]
> > Can you try again?
> > You should see this.
> > ```
> > error {
> >   error: 'Bad Request',
> >   message: 'transaction submit error ShelleyTxValidationError ShelleyBasedEraAlonzo (ApplyTxError [UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (OutputTooSmallUTxO [(Addr Testnet (KeyHashObj (KeyHash "0743d16cfe3c4fcc0c11c2403bbc10dbc7ecdd4477e053481a368e7a")) (StakeRefBase (KeyHashObj (KeyHash "06e2ae44dff6770dc0f4ada3cf4cf2605008e27aecdb332ad349fda7"))),Value 1000 (fromList []),SNothing)]))),UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (ValueNotConservedUTxO (Value 1000000000 (fromList [])) (Value 187973 (fromList []))))),UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (OutsideValidityIntervalUTxO (ValidityInterval {invalidBefore = SNothing, invalidHereafter = SJust (SlotNo 37079907)}) (SlotNo 37083558))))])',
> >   status_code: 400
> > }
> > ```
> 
> yes now i see 400 error, but why? is my transaction incorrect?

From the error I can see `OutputTooSmallUTxO`.
