### ISSUE TITLE
Wrong Metadata

### ISSUE THREAD

**Issue by TheLegendaryRainbowWarrior** [blockfrost/blockfrost-js#125]
Hello,

when I call the API, I don't get the correct data from "metadataTxsLabels" but I get the data from "metadataTxsLabel".

When I call "metadataTxsLabel", I get:

{
  status_code: 404,
  error: 'not found',
  message: 'The requested component was not found'.
}

I think there is something wrong.

Regards.

**Comment by vladimirvolek** [comment]
Hi!

Thank you for your message. I will look into it.

**Comment by TheLegendaryRainbowWarrior** [comment]
I think I was mistaken

**Comment by vladimirvolek** [comment]
We have incorrect types in metadata endpoints. :/

**Comment by TheLegendaryRainbowWarrior** [comment]
No problem!

**Comment by vladimirvolek** [comment]
Can you please send your whole request with the data?

**Comment by vladimirvolek** [comment]
@TheLegendaryRainbowWarrior Please send your code.

**Comment by TheLegendaryRainbowWarrior** [comment]
> @TheLegendaryRainbowWarrior Please send your code.

```
import { BlockFrostAPI } from '@blockfrost/blockfrost-js';

const contract = '....';

const API = new BlockFrostAPI({
  projectId: '...',
});

//const addressTXs = await API.metadataTxsLabels(contract);
const txLabels = await API.metadataTxsLabel(contract);

//console.log(addressTXs);
console.log(txLabels);
```

Output:

```
❯ node api.js

internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^
{
  status_code: 404,
  error: 'Not Found',
  message: 'The requested component has not been found.'
}
```

**Comment by vladimirvolek** [comment]
What is the `contract` varriable?

**Comment by TheLegendaryRainbowWarrior** [comment]
> What is the `contract` variable?

contract = [smart contract address](https://cardanoscan.io/address/addr1w83xtd6pekdv93xkj4qz77a5edyuhcxeuvlwex3xm0afukgj73l65)

Sorry, that was my mistake, I wanted to query the Oracle metadata with the contract address, which is of course nonsense and must run via the label ID. Now everything works correctly and I get the data. I just wanted to test the API a little. Great stuff!

```
// Smart Contract address from PIGY Oracle
const contract = 'addr1w83xtd6pekdv93xkj4qz77a5edyuhcxeuvlwex3xm0afukgj73l65';

const API = new BlockFrostAPI({
  projectId: '<MY_PROJECT_ID>',
});

const addressTXs = await API.metadataTxsLabels(contract);
const txLabels = await API.metadataTxsLabel('247428');

console.log(addressTXs);
console.log(txLabels);
```

**Comment by mkazlauskas** [comment]
> We have incorrect types in metadata endpoints. :/

The types are still incorrect for [Transaction metadata](https://docs.blockfrost.io/#tag/Cardano-Transactions/paths/~1txs~1{hash}~1metadata/get) endpoint
