### ISSUE TITLE
Metadata comes as null when trying to get asset detail

### ISSUE THREAD

**Issue by Manik-Jain** [blockfrost/blockfrost-js#138]
https://cardano-testnet.blockfrost.io/api/v0/assets/9c75d5ba05165a474488493fd9efc7555e407b104ad0b953114d89284c4f47494e5f544f4b454e

**Comment by Manik-Jain** [comment]
> > The token has metadata on-chain, but Blockfrost call returns null.
> > Proof : https://testnet.cardanoscan.io/transaction/6534385409b69f10c35ff1a3ebd6c14ce426daa9f80f865458830e53f28fc10e?tab=metadata
> > Response from blockfrost :
> > { "asset": "9c75d5ba05165a474488493fd9efc7555e407b104ad0b953114d89284c4f47494e5f544f4b454e", "policy_id": "9c75d5ba05165a474488493fd9efc7555e407b104ad0b953114d8928", "asset_name": "4c4f47494e5f544f4b454e", "fingerprint": "asset1zuslc2nzk8jmc8wkhyp6c5yw0rkz7973x9ffr7", "quantity": "1", "initial_mint_tx_hash": "6534385409b69f10c35ff1a3ebd6c14ce426daa9f80f865458830e53f28fc10e", "mint_or_burn_count": 1, "onchain_metadata": null, "metadata": null }
> 
> Hi @Manik-Jain, thanks for the report. After further investigation, we have found out that the submitted metadata are missing the correct label, which should be `721`. As you can see, the label is `0`. Both `label` and the `JSON` should include the same key, `721`. It seems that blockfrost handles the case correctly. If you agree, I'm going to close the issue.
> 
> ![image](https://user-images.githubusercontent.com/791309/139291960-1536746e-a9ee-408a-97db-8e2387b42863.png)

Hi @1000101 ,

Thanks for the insight. 
I tend to agree to with you, and then I think there are a few things that need to be re-considered :

1. The 721 standard is not yet "standardised" for Cardano, and we are just buying in the ERC standard [721 where was an auto-generated random number], which in future can change for Cardano change. Which is why, I think too much dependency on this string as a label may need re-work
2. There are different metadata labels being used by different developers at the moment, and even in the past. This would mean that whole bunch of that data will never be fetched? See here : https://cardano-testnet.blockfrost.io/api/v0/metadata/txs/labels
3. Transaction end point in Blockfrost fetches the metadata with `label : 0` or what-so-ever label for that matter.

**Comment by mmahut** [comment]
hello @Manik-Jain, we're supporting the current format as it is part of the [CIP-25](https://github.com/cardano-foundation/CIPs/blob/master/CIP-0025/CIP-0025.md).

If you think this standard can be improved (and I'm sure it can), I suggest to submit a CIP and if accepted, we will consider supporting it as the `onchain_metata` for sure.
