### ISSUE TITLE
Could you please share the sample code for Minting NFT by using the Blockfrost-js library?

### ISSUE THREAD

**Issue by firojalamkhan786** [blockfrost/blockfrost-js#182]
I want to mint NFT by using the Blockfrost-js library, Please provide the complete steps that are required for doing that. 
Please share the working example code.
1. How to construct the transaction object and what are mandatory details and what are the optional details. 
2. How to calculate the transaction fees
3. How to sign the transaction
4. How to pass the account details to the transaction object
5. To create the account object what are details required from the frontend application and which format those details - (I am trying to connect the Cardano supported wallet )
6. If you have any advice on which wallet I can able to use it that will be great, I am currently developing the DApp in the Cardano testnet.

**Comment by firojalamkhan786** [comment]
Thank you for your response.

**Comment by slowbackspace** [comment]
@firojalamkhan786 We've just merged an example on how to build a simple transaction and push it to the blockchain. It will not mint an NFT for you, but it should provide the basics for integrating Blockfrost into the process.

If you don't mind I'll close this issue. If you have any problem while using the SDK don't hesitate to open a new one.
