### ISSUE TITLE
Can't use library, ECONNRESET error

### ISSUE THREAD

**Issue by BlakeBrown** [blockfrost/blockfrost-js#183]
Hi there!

For some reason I always get the following error when querying with the client.

```js
BlockfrostClientError: read ECONNRESET
    at handleError (/Users/blakebrown/Documents/Code/wagmi/node_modules/@blockfrost/blockfrost-js/lib/utils/errors.js:60:12)
    at /Users/blakebrown/Documents/Code/wagmi/node_modules/@blockfrost/blockfrost-js/lib/endpoints/api/addresses/index.js:12:59
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ECONNRESET'
```

![image](https://user-images.githubusercontent.com/6283620/150186674-b494abf3-207b-4878-8d81-fe2293225aa5.png)

I have checked and my API key is correct. Any idea what could be causing this?

**Comment by vladimirvolek** [comment]
@BlakeBrown If you still have the problem feel free to reopen :)))
