### ISSUE TITLE
SDK breaks when using webpack 5

### ISSUE THREAD

**Issue by andywoodruff6** [blockfrost/blockfrost-js#193]
## Problem
Blockfrost sdk compiles with problems that are related to webpack 5.
`BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.`

## Steps to reproduce

1. Start a new create-react-app
2. install Blockfrost
3. call Blockfrost in App.js

## package.json
`  "dependencies": { 
    "@blockfrost/blockfrost-js": "^4.0.1",
    "@testing-library/jest-dom": "^5.16.2",
    "@testing-library/react": "^12.1.3",
    "@testing-library/user-event": "^13.5.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "5.0.0"
  }, `
^ is the default dependencies

**Comment by vladimirvolek** [comment]
This is a node js SDK (backend). You are building react (frontend) app.
