### ISSUE TITLE
README.md - Missing examples/ Directory

### ISSUE THREAD

**Issue by jasteele12** [blockfrost/blockfrost-js#252]
> For more examples take a look in [examples](https://github.com/blockfrost/blockfrost-js/blob/master/examples) directory.

Clicking the link brings up a 404 page, with this error message:

The 'blockfrost/blockfrost-js' repository doesn't contain the 'examples' path in 'master'.

**Comment by vladimirvolek** [comment]
Thank you 💕 
We have moved the examples here https://github.com/blockfrost/blockfrost-js-examples
