### ISSUE TITLE
Add coinsPerUTxOByte to Epoch response

### ISSUE THREAD

**Issue by mahnunchik** [blockfrost/blockfrost-js#268]
According to the documentation parameter `coinsPerUTxOByte` needed for minimum ada value calculation.

https://docs.cardano.org/native-tokens/minimum-ada-value-requirement

**Comment by sorki** [comment]
Hi, this is available via `epochsParameters` and `epochsLatestParameters` (https://docs.blockfrost.io/#tag/Cardano-Epochs/paths/~1epochs~1latest~1parameters/get) except the value is called `coins_per_utxo_size`. The description of the field is

```
Cost per UTxO word for Alonzo. Cost per UTxO byte for Babbage and later.
```
