### ISSUE TITLE
blockfrost api.epochsStakesByPoolIdAll it sometimes gives me wrong data.

### ISSUE THREAD

**Issue by golddydev** [blockfrost/blockfrost-js#287]
I am fetching delegators data using blockfrost api.

This is the function I use.
```
API.epochsStakesByPoolIdAll(epochNumber, poolId);
```

And it sometimes gave me wrong data (less than real)
When I test at the very begining of epoch, and test with that epoch number.

For example, now epoch 436 just started, and I call 
```
API.epochsStakesByPoolIdAll(436, poolId);
```
then it gave me wrong data (less than actual delegators)

Does this api need some time to prepare all of its data from blockchain?

**Comment by slowbackspace** [comment]
Hi @golddydev, sorry for the late reply. Are you still experiencing issue? Could you post an example of the call and inccorect response?

**Comment by vladimirvolek** [comment]
@golddydev If you still have the issue, feel free to reopen.

**Comment by golddydev** [comment]
Yeah, it is fixed, now.
