### ISSUE TITLE
"GET /txs/{hash}/cbor" functionality

### ISSUE THREAD

**Issue by ginnun** [blockfrost/blockfrost-js#298]
Hello there,

I am trying to figure out how to get data from `/txs/{hash}/cbor`. 
Is it exposed in the blockfrost-js client? Is there any workaround I could do?

As a workaround, I am going to use:
  `  const response = await this.blockfrost.instance<Schemas['script_cbor']>('/txs/${hash}/cbor');`

**Comment by slowbackspace** [comment]
Hi, I just opened [PR](https://github.com/blockfrost/blockfrost-js/pull/299) with the method for CBOR endpoint, but you workaround will work just fine in the meantime :)

**Comment by slowbackspace** [comment]
`@blockfrost/blockfrost-js@5.6.0-beta.2` is now in NPM with `BlockfrostAPI.txsCbor(hash)` method.
